# Site settings
title: MooFoo blogs
email: shybovycha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My greatest thoughts are written down here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shybovycha.github.io/" # the base hostname & protocol for your site
twitter_username: shybovycha
github_username:  shybovycha
excerpt_separator: '<!--more-->'
paginate: 10
highlighter: rouge
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
exclude: ['bower_components', 'node_modules', 'package.json', 'bower.json', '_sass', '_js', '_css', '.sass-cache', 'main.js']
