# Site settings
title: MooFoo blogs
email: shybovycha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My greatest thoughts are written down here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shybovycha.github.io" # the base hostname & protocol for your site
twitter_username: shybovycha
github_username:  shybovycha
excerpt_separator: '<!--more-->'
paginate: 10
highlighter: rouge
plugins: [jekyll-paginate, jemoji, jekyll-sitemap]

# Build settings
markdown: kramdown

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []
